version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - nilnil
    - wsl
  enable:
    - useany
  settings:
    custom:
      useany:
        type: module
        description: Enforces using 'any' instead of 'interface{}'